{
  "openapi": "3.1.0",
  "info": {
    "title": "ArbaeenTV",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/api/auth/login": {
      "post": {
        "summary": "Login",
        "deprecated": false,
        "description": "### Login\n\nUsed for both admin and user login.\n\n#### Parameters\n\n| **Parameter** | **Rules** |\n| --- | --- |\n| phone_number | required  <br>string  <br>valid  <br>format: 09######### |\n| password | required  <br>string |",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "phone_number": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "required": [
                  "phone_number",
                  "password"
                ]
              },
              "example": {
                "phone_number": "09121111111",
                "password": "Admin@12135"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "token": {
                          "type": "string"
                        },
                        "user": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "integer"
                            },
                            "phone_number": {
                              "type": "string"
                            },
                            "created_at": {
                              "type": "string"
                            },
                            "updated_at": {
                              "type": "string"
                            }
                          },
                          "required": [
                            "id",
                            "phone_number",
                            "created_at",
                            "updated_at"
                          ]
                        }
                      },
                      "required": [
                        "token",
                        "user"
                      ]
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "status": "success",
                  "data": {
                    "token": "16|u6BR6WDTUeUPTMjey31KHpp5VnnzuKYCN7u51Zaf419b11d1",
                    "user": {
                      "id": 1,
                      "phone_number": "09121111111",
                      "created_at": "2025-12-02 20:23:07",
                      "updated_at": "2025-12-02 20:23:07"
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/auth/logout": {
      "post": {
        "summary": "Logout",
        "deprecated": false,
        "description": "### Logout\n\nUse for both admin and user logout. Just need token.",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "status",
                    "message"
                  ]
                },
                "example": {
                  "status": "success",
                  "message": "با موفقیت از حساب کاربری خارج شدید"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/channel/create": {
      "post": {
        "summary": "New Channel",
        "deprecated": false,
        "description": "### New Channel\n\nWith this endpoint ypu can create new channel. For this endpoint need token and below rules.\n\n#### Parameters\n\n| **Parameter** | **Rules** |\n| --- | --- |\n| name | required  <br>string  <br>unique |\n| user_id | optional  <br>int  <br>exists |",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "user_id": {
                    "type": "integer"
                  }
                },
                "required": [
                  "name",
                  "user_id"
                ]
              },
              "example": {
                "name": "Test Channel 3",
                "user_id": 1
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "name",
                        "created_at",
                        "updated_at"
                      ]
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "status": "success",
                  "data": {
                    "id": 3,
                    "name": "Test Channel 3",
                    "created_at": "2025-12-08 09:07:21",
                    "updated_at": "2025-12-08 09:07:21"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/channel": {
      "get": {
        "summary": "Channels",
        "deprecated": false,
        "description": "### Channels\n\nWith this endpoint you can get all of channels.",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "name": {
                            "type": "string"
                          },
                          "created_at": {
                            "type": "string"
                          },
                          "updated_at": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "id",
                          "name",
                          "created_at",
                          "updated_at"
                        ]
                      }
                    },
                    "links": {
                      "type": "object",
                      "properties": {
                        "first": {
                          "type": "string"
                        },
                        "last": {
                          "type": "string"
                        },
                        "prev": {
                          "type": "null"
                        },
                        "next": {
                          "type": "null"
                        }
                      },
                      "required": [
                        "first",
                        "last",
                        "prev",
                        "next"
                      ]
                    },
                    "meta": {
                      "type": "object",
                      "properties": {
                        "current_page": {
                          "type": "integer"
                        },
                        "from": {
                          "type": "integer"
                        },
                        "last_page": {
                          "type": "integer"
                        },
                        "links": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "url": {
                                "type": [
                                  "string",
                                  "null"
                                ]
                              },
                              "label": {
                                "type": "string"
                              },
                              "page": {
                                "type": [
                                  "integer",
                                  "null"
                                ]
                              },
                              "active": {
                                "type": "boolean"
                              }
                            },
                            "required": [
                              "url",
                              "label",
                              "page",
                              "active"
                            ]
                          }
                        },
                        "path": {
                          "type": "string"
                        },
                        "per_page": {
                          "type": "integer"
                        },
                        "to": {
                          "type": "integer"
                        },
                        "total": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "current_page",
                        "from",
                        "last_page",
                        "links",
                        "path",
                        "per_page",
                        "to",
                        "total"
                      ]
                    }
                  },
                  "required": [
                    "status",
                    "data",
                    "links",
                    "meta"
                  ]
                },
                "example": {
                  "status": "success",
                  "data": [
                    {
                      "id": 1,
                      "name": "Test Channel 2",
                      "created_at": "2025-12-02 20:23:52",
                      "updated_at": "2025-12-02 20:23:52"
                    },
                    {
                      "id": 2,
                      "name": "Test Channel",
                      "created_at": "2025-12-03 12:45:22",
                      "updated_at": "2025-12-03 12:45:22"
                    }
                  ],
                  "links": {
                    "first": "http://localhost/api/channel?page=1",
                    "last": "http://localhost/api/channel?page=1",
                    "prev": null,
                    "next": null
                  },
                  "meta": {
                    "current_page": 1,
                    "from": 1,
                    "last_page": 1,
                    "links": [
                      {
                        "url": null,
                        "label": "&laquo; Previous",
                        "page": null,
                        "active": false
                      },
                      {
                        "url": "http://localhost/api/channel?page=1",
                        "label": "1",
                        "page": 1,
                        "active": true
                      },
                      {
                        "url": null,
                        "label": "Next &raquo;",
                        "page": null,
                        "active": false
                      }
                    ],
                    "path": "http://localhost/api/channel",
                    "per_page": 25,
                    "to": 2,
                    "total": 2
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/channel/{channel_id}": {
      "get": {
        "summary": "Channel",
        "deprecated": false,
        "description": "### Channel\n\nWith this enpoint ypu can get specific channel. Need channel id in Url.",
        "tags": [],
        "parameters": [
          {
            "name": "channel_id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "name",
                        "created_at",
                        "updated_at"
                      ]
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "status": "success",
                  "data": {
                    "id": 1,
                    "name": "Test Channel 2",
                    "created_at": "2025-12-02 20:23:52",
                    "updated_at": "2025-12-02 20:23:52"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/channel/update/{channel_id}": {
      "put": {
        "summary": "Update",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "channel_id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "user_id": {
                    "type": "integer"
                  }
                },
                "required": [
                  "name",
                  "user_id"
                ]
              },
              "example": {
                "name": "test channel",
                "user_id": 2
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "name": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "name",
                        "created_at",
                        "updated_at"
                      ]
                    }
                  },
                  "required": [
                    "status",
                    "data"
                  ]
                },
                "example": {
                  "status": "success",
                  "data": {
                    "id": 1,
                    "name": "updated name",
                    "created_at": "2025-12-02 20:23:52",
                    "updated_at": "2025-12-08 09:43:01"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/channel/delete/{channel_id}": {
      "delete": {
        "summary": "Delete",
        "deprecated": false,
        "description": "With this endpoint you can delete existing channel. Just need token and channel id in url.",
        "tags": [],
        "parameters": [
          {
            "name": "channel_id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": "success",
                  "message": "کانال با موفقیت حذف شد"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/video/{channel_id}/store-video": {
      "post": {
        "summary": "Store Video",
        "deprecated": false,
        "description": "### Store video\n\nWith this endpoint yopu can attach uploaded video to an existing channel.\n\nFor this endpoint need token and below rules:\n\n#### Parameters\n\n| **Parameter** | **Rules** |\n| --- | --- |\n| path | required  <br>string  <br>exists |\n| title | required  <br>string |\n| description | optional  <br>string |\n| cover | optional  <br>file  <br>formats: jpg, png, jpeg |",
        "tags": [],
        "parameters": [
          {
            "name": "channel_id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "path": {
                    "example": "temp/692f4ca8ce8f0.mp4",
                    "type": "string"
                  },
                  "title": {
                    "example": "test title 2",
                    "type": "string"
                  },
                  "description": {
                    "example": "test description 2",
                    "type": "string"
                  },
                  "cover": {
                    "description": "valid formats: jpg",
                    "type": "string",
                    "format": "binary"
                  }
                },
                "required": [
                  "path",
                  "title",
                  "description",
                  "cover"
                ]
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/video/upload": {
      "post": {
        "summary": "Upload",
        "deprecated": false,
        "description": "Document in html file.",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/video/{channel_id}": {
      "get": {
        "summary": "Get videos",
        "deprecated": false,
        "description": "### Get Videos\n\nWith this endpoint you can get videos of specific channel.",
        "tags": [],
        "parameters": [
          {
            "name": "channel_id",
            "in": "path",
            "description": "optional",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "path": {
                    "example": "temp/692f4b1ce20fe.mp4",
                    "type": "string"
                  },
                  "title": {
                    "example": "test title",
                    "type": "string"
                  },
                  "description": {
                    "example": "test description",
                    "type": "string"
                  },
                  "cover": {
                    "description": "valid formats: jpg",
                    "type": "string",
                    "format": "binary"
                  }
                },
                "required": [
                  "path",
                  "title",
                  "description",
                  "cover"
                ]
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/video/show/{video_id}": {
      "get": {
        "summary": "Video",
        "deprecated": false,
        "description": "### Video\n\nWith this endpoint you can get specific video.",
        "tags": [],
        "parameters": [
          {
            "name": "video_id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "path": {
                    "example": "temp/692f4b1ce20fe.mp4",
                    "type": "string"
                  },
                  "title": {
                    "example": "test title",
                    "type": "string"
                  },
                  "description": {
                    "example": "test description",
                    "type": "string"
                  },
                  "cover": {
                    "description": "valid formats: jpg",
                    "type": "string",
                    "format": "binary"
                  }
                },
                "required": [
                  "path",
                  "title",
                  "description",
                  "cover"
                ]
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/video": {
      "get": {
        "summary": "All videos",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "example": "application/json",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "integer"
                          },
                          "channel_name": {
                            "type": "string"
                          },
                          "cover_link": {
                            "type": "string"
                          },
                          "title": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "id",
                          "channel_name",
                          "cover_link",
                          "title"
                        ]
                      }
                    },
                    "links": {
                      "type": "object",
                      "properties": {
                        "first": {
                          "type": "string"
                        },
                        "last": {
                          "type": "string"
                        },
                        "prev": {
                          "type": "null"
                        },
                        "next": {
                          "type": "null"
                        }
                      },
                      "required": [
                        "first",
                        "last",
                        "prev",
                        "next"
                      ]
                    },
                    "meta": {
                      "type": "object",
                      "properties": {
                        "current_page": {
                          "type": "integer"
                        },
                        "from": {
                          "type": "integer"
                        },
                        "last_page": {
                          "type": "integer"
                        },
                        "links": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "url": {
                                "type": [
                                  "string",
                                  "null"
                                ]
                              },
                              "label": {
                                "type": "string"
                              },
                              "page": {
                                "type": [
                                  "integer",
                                  "null"
                                ]
                              },
                              "active": {
                                "type": "boolean"
                              }
                            },
                            "required": [
                              "url",
                              "label",
                              "page",
                              "active"
                            ]
                          }
                        },
                        "path": {
                          "type": "string"
                        },
                        "per_page": {
                          "type": "integer"
                        },
                        "to": {
                          "type": "integer"
                        },
                        "total": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "current_page",
                        "from",
                        "last_page",
                        "links",
                        "path",
                        "per_page",
                        "to",
                        "total"
                      ]
                    }
                  },
                  "required": [
                    "status",
                    "data",
                    "links",
                    "meta"
                  ]
                },
                "example": {
                  "status": "success",
                  "data": [
                    {
                      "id": 3,
                      "channel_name": "updated name",
                      "cover_link": "http://localhost:80/storage/3/692f4ca8ce8f0.mp4",
                      "title": "test title 2"
                    },
                    {
                      "id": 2,
                      "channel_name": "updated name",
                      "cover_link": "http://localhost:80/storage/2/692f4b1ce20fe.mp4",
                      "title": "test title"
                    },
                    {
                      "id": 1,
                      "channel_name": "updated name",
                      "cover_link": "http://localhost:80/storage/1/692f4b1ce20fe.mp4",
                      "title": "test title"
                    }
                  ],
                  "links": {
                    "first": "http://localhost/api/video?page=1",
                    "last": "http://localhost/api/video?page=1",
                    "prev": null,
                    "next": null
                  },
                  "meta": {
                    "current_page": 1,
                    "from": 1,
                    "last_page": 1,
                    "links": [
                      {
                        "url": null,
                        "label": "&laquo; Previous",
                        "page": null,
                        "active": false
                      },
                      {
                        "url": "http://localhost/api/video?page=1",
                        "label": "1",
                        "page": 1,
                        "active": true
                      },
                      {
                        "url": null,
                        "label": "Next &raquo;",
                        "page": null,
                        "active": false
                      }
                    ],
                    "path": "http://localhost/api/video",
                    "per_page": 25,
                    "to": 3,
                    "total": 3
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/video/delete/{video_id}": {
      "delete": {
        "summary": "Delete Video",
        "deprecated": false,
        "description": "With this endpoint you can delete specific video. Just need token and video id.",
        "tags": [],
        "parameters": [
          {
            "name": "video_id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": "success",
                  "message": "ویدئو با موفقیت پاک شد"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    }
  },
  "webhooks": {},
  "components": {
    "schemas": {},
    "responses": {},
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [
    {
      "url": "localhost:80",
      "description": "ArbaeenTV"
    }
  ],
  "security": []
}